In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rakeshrau/social-network-ads/Social_Network_Ads.csv


In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv("/kaggle/input/datasets/rakeshrau/social-network-ads/Social_Network_Ads.csv")

In [7]:
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [8]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [10]:
df.describe()

,User ID,Age,EstimatedSalary,Purchased
count,4.000000e+02,400.000000,400.000000,400.000000
mean,1.569154e+07,37.655000,69742.500000,0.357500
std,7.165832e+04,10.482877,34096.960282,0.479864
min,1.556669e+07,18.000000,15000.000000,0.000000
25%,1.562676e+07,29.750000,43000.000000,0.000000
50%,1.569434e+07,37.000000,70000.000000,0.000000
75%,1.575036e+07,46.000000,88000.000000,1.000000
max,1.581524e+07,60.000000,150000.000000,1.000000


In [11]:
df.drop(["User ID"],axis=1)

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0
...,...,...,...,...
395,Female,46,41000,1
396,Male,51,23000,1
397,Female,50,20000,1
398,Male,36,33000,0


In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])

In [13]:
df["Gender"]

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: Gender, Length: 400, dtype: int64

In [14]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,1,19,19000,0
1,15810944,1,35,20000,0
2,15668575,0,26,43000,0
3,15603246,0,27,57000,0
4,15804002,1,19,76000,0


In [15]:
X= df.drop("Purchased", axis=1)
y=df["Purchased"]

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size= 0.20, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.8875

In [20]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[50,  2],
       [ 7, 21]])

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92        52
           1       0.91      0.75      0.82        28

    accuracy                           0.89        80
   macro avg       0.90      0.86      0.87        80
weighted avg       0.89      0.89      0.88        80



In [22]:
X2= df.drop(["Purchased","Gender"],axis=1)
y = df["Purchased"]

In [23]:
from sklearn.model_selection import train_test_split

X2_train,X2_test,y_train,y_test=train_test_split(X2,y, test_size=0.2, random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(X2_train,y_train)

LogisticRegression()

In [25]:
y_pred_2 = model.predict(X2_test)

In [26]:
from sklearn.metrics import accuracy_score

accuracy_score(y_pred_2,y_test)

0.8875

In [27]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_2)

array([[50,  2],
       [ 7, 21]])

In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_2))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92        52
           1       0.91      0.75      0.82        28

    accuracy                           0.89        80
   macro avg       0.90      0.86      0.87        80
weighted avg       0.89      0.89      0.88        80



In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [30]:
X2_train_scaled = scaler.fit_transform(X2_train)
X2_test_scaled = scaler.transform(X2_test)

In [31]:
from sklearn.linear_model import LogisticRegression

model_1= LogisticRegression()
model_1.fit(X2_train_scaled,y_train)

LogisticRegression()

In [32]:
y_pred_3 = model_1.predict(X2_test_scaled)

In [33]:
from sklearn.metrics import accuracy_score

accuracy_score(y_pred_3,y_test)

0.8625

In [34]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred_3)



array([[50,  2],
       [ 9, 19]])

In [35]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_3))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90        52
           1       0.90      0.68      0.78        28

    accuracy                           0.86        80
   macro avg       0.88      0.82      0.84        80
weighted avg       0.87      0.86      0.86        80



#Knn model trainning

In [36]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 12)

knn.fit(X2_train,y_train)


KNeighborsClassifier(n_neighbors=12)

In [37]:
y_pred_knn = knn.predict(X2_test)

In [38]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred_knn)

0.725

In [39]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred_knn)

array([[48,  4],
       [18, 10]])

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.73      0.92      0.81        52
           1       0.71      0.36      0.48        28

    accuracy                           0.72        80
   macro avg       0.72      0.64      0.64        80
weighted avg       0.72      0.72      0.70        80



In [41]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X2_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=7)

In [42]:
y_pred_knn_2 = knn.predict(X2_test_scaled)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_knn_2)

0.95

In [44]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred_knn_2)

array([[49,  3],
       [ 1, 27]])

In [45]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred_knn_2))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96        52
           1       0.90      0.96      0.93        28

    accuracy                           0.95        80
   macro avg       0.94      0.95      0.95        80
weighted avg       0.95      0.95      0.95        80



#Desicion tree

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
model_DT = DecisionTreeClassifier(random_state=42)

In [49]:
model_DT.fit(X2_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [52]:
y_pred_DT = model_DT.predict(X2_test_scaled)

In [53]:
accuracy_score(y_test,y_pred_DT)

0.875

In [54]:
confusion_matrix(y_test,y_pred_DT)

array([[47,  5],
       [ 5, 23]])

In [55]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90        52
           1       0.82      0.82      0.82        28

    accuracy                           0.88        80
   macro avg       0.86      0.86      0.86        80
weighted avg       0.88      0.88      0.88        80

